services:
  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
volumes:
  pgdata: